### ISSUE TITLE
Can't import package

### ISSUE THREAD

**Issue by dliu-fn** [Yard1/hpbandster-sklearn#2]
```
>>> import hpbandster_sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py", line 1, in <module>
    from .HpBandSterSearchCV import HpBandSterSearchCV
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/HpBandSterSearchCV.py", line 21, in <module>
    import hpbandster.core.nameserver as hpns
  File "/Users/davidliu/dyson-sync/hpbandster/hpbandster.py", line 13, in <module>
    search = HpBandSterSearchCV(clf, param_distributions,random_state=0, n_jobs=1, n_iter=10, verbose=1)
TypeError: 'module' object is not callable
```

**Comment by Yard1** [comment]
Can you try `from hpbandster_sklearn import HpBandSterSearchCV`? This should work in the meantime. I'll fix this asap.

**Comment by dliu-fn** [comment]
I tried that too, but same issue.
```
>>> from hpbandster_sklearn import HpBandSterSearchCV
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py", line 1, in <module>
    from .HpBandSterSearchCV import HpBandSterSearchCV
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/HpBandSterSearchCV.py", line 21, in <module>
    import hpbandster.core.nameserver as hpns
  File "/Users/davidliu/dyson-sync/hpbandster/hpbandster.py", line 13, in <module>
    search = HpBandSterSearchCV(clf, param_distributions,random_state=0, n_jobs=1, n_iter=10, verbose=1)
TypeError: 'module' object is not callable
```

**Comment by dliu-fn** [comment]
I wonder if it's some sort of issue with the class sharing the same name as the file... 
https://stackoverflow.com/questions/42127593/should-python-class-filenames-also-be-camelcased/42127721

What if we tried making the file lowercase `hpbandstersearchcv.py` or maybe something shorter like `search_cv.py`. The process of renaming would help Python avoid the confusion between module and class.

**Comment by Yard1** [comment]
Hey, I can't replicate this locally.
```
(hpbandster-sklearn) ➜  hpbandster-sklearn git:(master) ✗ python
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hpbandster_sklearn
>>> hpbandster_sklearn.HpBandSterSearchCV
<class 'hpbandster_sklearn.HpBandSterSearchCV.HpBandSterSearchCV'>
>>> 
```

However, this could be an issue with filenames, which should probably be resolved regardless. I'll make a new branch - can you then install from it and see if it fixes the issue?

**Comment by Yard1** [comment]
Could you try `pip install -U git+https://github.com/Yard1/hpbandster-sklearn.git@change_file_case` in the virtual env?

**Comment by dliu-fn** [comment]
Yeah, tried but still getting the same issue.

**Comment by dliu-fn** [comment]
Ok, so I tried running it on a remote cluster, and now I'm getting a different error:

```
(hpbandster) $ python hpbandster.py 
Traceback (most recent call last):
  File "hpbandster.py", line 5, in <module>
    from hpbandster_sklearn import HpBandSterSearchCV
  File "/home/dliu/.virtualenvs/hpbandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py", line 1, in <module>
    from .search_cv import HpBandSterSearchCV
  File "/home/dliu/.virtualenvs/hpbandster/lib/python3.8/site-packages/hpbandster_sklearn/search_cv.py", line 21, in <module>
    import hpbandster.core.nameserver as hpns
  File "/home/dliu/dyson-sync/hpbandster/hpbandster.py", line 5, in <module>
    from hpbandster_sklearn import HpBandSterSearchCV
ImportError: cannot import name 'HpBandSterSearchCV' from partially initialized module 'hpbandster_sklearn'
```

Looks like we need to do `from __future__ import annotations`
https://stackoverflow.com/questions/61544854/from-future-import-annotations

**Comment by Yard1** [comment]
Are you running this on Mac? What's your Python version?

**Comment by dliu-fn** [comment]
So for:
```
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.validation import check_is_fitted
from hpbandster_sklearn import HpBandSterSearchCV

X, y = load_iris(return_X_y=True)
clf = RandomForestClassifier(random_state=0)
np.random.seed(0)

param_distributions = {"max_depth": [2, 3, 4], "min_samples_split": list(range(2, 12))}

search = HpBandSterSearchCV(clf, param_distributions,random_state=0, n_jobs=1, n_iter=10, verbose=1)
search.fit(X, y)
print(search.best_params_)
```

my Mac Python 3.8.6 local, gives:
```
Traceback (most recent call last):
  File "hpbandster.py", line 7, in <module>
    from hpbandster_sklearn import HpBandSterSearchCV
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py", line 1, in <module>
    from .HpBandSterSearchCV import HpBandSterSearchCV
  File "/Users/davidliu/.virtualenvs/bandster/lib/python3.8/site-packages/hpbandster_sklearn/HpBandSterSearchCV.py", line 21, in <module>
    import hpbandster.core.nameserver as hpns
  File "/Users/davidliu/dyson-sync/hpbandster/hpbandster.py", line 15, in <module>
    search = HpBandSterSearchCV(clf, param_distributions,random_state=0, n_jobs=1, n_iter=10, verbose=1)
TypeError: 'module' object is not callable
```

Linux 3.8.6 on cluster, gives 
```
ImportError: cannot import name 'HpBandSterSearchCV' from partially initialized
module 'hpbandster_sklearn' (most likely due to a circular import)
(/home/dliu/.virtualenvs/hpbandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py)
```

**Comment by Yard1** [comment]
This is very odd considering that the tests both on my machine and on github actions pass. Could you try with a new virtual environment?

**Comment by dliu-fn** [comment]
Ok, running `pip install -U git+https://github.com/Yard1/hpbandster-sklearn.git@change_file_case` on local Mac(3.8.6)

Yep, started a brand-new environment, same issue:

```
ImportError: cannot import name 'HpBandSterSearchCV' from partially initialized module 'hpbandster_sklearn' (most likely due to a circular import) (/Users/davidliu/.virtualenvs/test_hpbandster/lib/python3.8/site-packages/hpbandster_sklearn/__init__.py)
```

So it seems like by using `pip install -U git+https://github.com/Yard1/hpbandster-sklearn.git@change_file_case` we get the `ImportError` and by running `pip install hpbandster_sklearn` we get the `TypeError`.

**Comment by dliu-fn** [comment]
**AHA** I called the file `hpbandster.py`, which I shouldn't have, which confused the Python module lookup. Successfully ran on local. Thank you for your responses.

**Comment by dliu-fn** [comment]
Can confirm after renaming file, can successfully run. Strangely, I still don't understand why Python console wasn't working...

**Comment by Yard1** [comment]
Glad you figured this out!
